BUILD_CONFIG = Debug

JD_DEBUGGER = gdb

JD_COMPILER = g++
JD_ARCHIVE = ar
JD_LIBRARY_EXTENSION = lib
JD_EXECUTABLE_EXTENSION = exe

JD_COMMON_CFLAGS = -Wall --std=c++23
JD_DEBUG_CFLAGS = -g -MMD
JD_RELEASE_CFLAGS = -O2

JD_COMMON_LDFLAGS = 
JD_DEBUG_LDFLAGS = 
JD_RELEASE_LDFLAGS = 

JD_CFLAGS =
JD_LDFLAGS = 

ifeq ($(BUILD_CONFIG), Debug)
	JD_CFLAGS = $(JD_COMMON_CFLAGS) $(JD_DEBUG_CFLAGS)
	JD_LDFLAGS = $(JD_COMMON_LDFLAGS) $(JD_DEBUG_LDFLAGS)
	JD_LIBS = $(JD_COMMON_LIBS) $(JD_DEBUG_LIBS)
	JD_LIBDIRS = $(JD_COMMON_LIBDIRS) $(JD_DEBUG_LIBDIRS)
else ifeq ($(BUILD_CONFIG), Release)
	JD_CFLAGS = $(JD_COMMON_CFLAGS) $(JD_RELEASE_CFLAGS)
	JD_LDFLAGS = $(JD_COMMON_LDFLAGS) $(JD_RELEASE_LDFLAGS)
	JD_LIBS = $(JD_COMMON_LIBS) $(JD_RELEASE_LIBS)
	JD_LIBDIRS = $(JD_COMMON_LIBDIRS) $(JD_RELEASE_LIBDIRS)
else
$(error "BUILD_CONFIG must be ether "Debug" or "Release")
endif

JD_SOURCE_DIR_NAME = Source
JD_BINARY_OUTPUT_DIR_NAME = Output
JD_BINARY_INTERMEDIATE_DIR_NAME = Intermediate

JADE_CORE = JadeCore
JADE_CORE_DIR = Jade/JadeCore
JADE_CORE_SOURCE_DIR = $(JADE_CORE_DIR)/$(JD_SOURCE_DIR_NAME)
JADE_CORE_BINARY_OUTPUT_DIR = $(JADE_CORE_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_OUTPUT_DIR_NAME)
JADE_CORE_BINARY_INTERMEDIATE_DIR = $(JADE_CORE_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_INTERMEDIATE_DIR_NAME)
JADE_CORE_OUTPUT_TARGET = $(JADE_CORE_BINARY_OUTPUT_DIR)/$(JADE_CORE).$(JD_LIBRARY_EXTENSION)
JADE_CORE_INCLUDE_DIRS = -I$(JADE_CORE_SOURCE_DIR)
JADE_CORE_DEBUG_LIBS =
JADE_CORE_RELEASE_LIBS =
JADE_CORE_DEBUG_LIBDIRS =
JADE_CORE_RELEASE_LIBDIRS =
JADE_CORE_LIBS =
JADE_CORE_LIBDIRS =

JADE_CLIENT = JadeClient
JADE_CLIENT_DIR = Jade/JadeClient
JADE_CLIENT_SOURCE_DIR = $(JADE_CLIENT_DIR)/$(JD_SOURCE_DIR_NAME)
JADE_CLIENT_BINARY_OUTPUT_DIR = $(JADE_CLIENT_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_OUTPUT_DIR_NAME)
JADE_CLIENT_BINARY_INTERMEDIATE_DIR = $(JADE_CLIENT_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_INTERMEDIATE_DIR_NAME)
JADE_CLIENT_OUTPUT_TARGET = $(JADE_CLIENT_BINARY_OUTPUT_DIR)/$(JADE_CLIENT).$(JD_LIBRARY_EXTENSION)
JADE_CLIENT_INCLUDE_DIRS = -I$(JADE_CLIENT_SOURCE_DIR) -I$(JADE_CORE_SOURCE_DIR)
JADE_CLIENT_DEBUG_LIBS = -l$(JADE_CORE)
JADE_CLIENT_RELEASE_LIBS = -l$(JADE_CORE)
JADE_CLIENT_DEBUG_LIBDIRS = -L$(JADE_CORE_BINARY_OUTPUT_DIR)
JADE_CLIENT_RELEASE_LIBDIRS = -L$(JADE_CORE_BINARY_OUTPUT_DIR)
JADE_CLIENT_LIBS = 
JADE_CLIENT_LIBDIRS =

JADE_SERVER = JadeServer
JADE_SERVER_DIR = Jade/JadeServer
JADE_SERVER_SOURCE_DIR = $(JADE_SERVER_DIR)/$(JD_SOURCE_DIR_NAME)
JADE_SERVER_BINARY_OUTPUT_DIR = $(JADE_SERVER_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_OUTPUT_DIR_NAME)
JADE_SERVER_BINARY_INTERMEDIATE_DIR = $(JADE_SERVER_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_INTERMEDIATE_DIR_NAME)
JADE_SERVER_OUTPUT_TARGET = $(JADE_SERVER_BINARY_OUTPUT_DIR)/$(JADE_SERVER).$(JD_LIBRARY_EXTENSION)
JADE_SERVER_INCLUDE_DIRS = -I$(JADE_SERVER_SOURCE_DIR) -I$(JADE_CORE_SOURCE_DIR)
JADE_SERVER_DEBUG_LIBS = -l$(JADE_CORE)
JADE_SERVER_RELEASE_LIBS = -l$(JADE_CORE)
JADE_SERVER_DEBUG_LIBDIRS = -L$(JADE_CORE_BINARY_OUTPUT_DIR)
JADE_SERVER_RELEASE_LIBDIRS = -L$(JADE_CORE_BINARY_OUTPUT_DIR)
JADE_SERVER_LIBS =
JADE_SERVER_LIBDIRS =

JADE_EDITOR = JadeEditor
JADE_EDITOR_DIR = Jade/JadeEditor
JADE_EDITOR_SOURCE_DIR = $(JADE_EDITOR_DIR)/$(JD_SOURCE_DIR_NAME)
JADE_EDITOR_BINARY_OUTPUT_DIR = $(JADE_EDITOR_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_OUTPUT_DIR_NAME)
JADE_EDITOR_BINARY_INTERMEDIATE_DIR = $(JADE_EDITOR_DIR)/Binaries/$(BUILD_CONFIG)/$(JD_BINARY_INTERMEDIATE_DIR_NAME)
JADE_EDITOR_OUTPUT_TARGET = $(JADE_EDITOR_BINARY_OUTPUT_DIR)/$(JADE_EDITOR).$(JD_EXECUTABLE_EXTENSION)
JADE_EDITOR_INCLUDE_DIRS = -I$(JADE_CORE_SOURCE_DIR) -I$(JADE_CLIENT_SOURCE_DIR) -I$(JADE_SERVER_SOURCE_DIR) -I$(JADE_EDITOR_SOURCE_DIR)
JADE_EDITOR_DEBUG_LIBS = -l$(JADE_CORE) -l$(JADE_CLIENT) -l$(JADE_SERVER)
JADE_EDITOR_RELEASE_LIBS = -l$(JADE_CORE) -l$(JADE_CLIENT) -l$(JADE_SERVER)
JADE_EDITOR_DEBUG_LIBDIRS = -L$(JADE_CORE_BINARY_OUTPUT_DIR) -L$(JADE_CLIENT_BINARY_OUTPUT_DIR) -L$(JADE_SERVER_BINARY_OUTPUT_DIR)
JADE_EDITOR_RELEASE_LIBDIRS = -L$(JADE_CORE_BINARY_OUTPUT_DIR) -L$(JADE_CLIENT_BINARY_OUTPUT_DIR) -L$(JADE_SERVER_BINARY_OUTPUT_DIR)
JADE_EDITOR_LIBS = 
JADE_EDITOR_LIBDIRS =

ifeq ($(BUILD_CONFIG), Debug)
	JD_CFLAGS = $(JD_COMMON_CFLAGS) $(JD_DEBUG_CFLAGS)
	JD_LDFLAGS = $(JD_COMMON_LDFLAGS) $(JD_DEBUG_LDFLAGS)

	JADE_CORE_LIBS = $(JADE_CORE_DEBUG_LIBS)
	JADE_CORE_LIBDIRS = $(JADE_CORE_DEBUG_LIBDIRS)

	JADE_CLIENT_LIBS = $(JADE_CORE_DEBUG_LIBS) $(JADE_CLIENT_DEBUG_LIBS)
	JADE_CLIENT_LIBDIRS = $(JADE_CORE_DEBUG_LIBDIRS) $(JADE_CLIENT_DEBUG_LIBDIRS)

	JADE_SERVER_LIBS = $(JADE_CORE_DEBUG_LIBS) $(JADE_SERVER_DEBUG_LIBS)
	JADE_SERVER_LIBDIRS = $(JADE_CORE_DEBUG_LIBDIRS) $(JADE_SERVER_DEBUG_LIBDIRS)

	JADE_EDITOR_LIBS = $(JADE_CORE_DEBUG_LIBS) $(JADE_CLIENT_DEBUG_LIBS) $(JADE_SERVER_DEBUG_LIBS) $(JADE_EDITOR_DEBUG_LIBS)
	JADE_EDITOR_LIBDIRS = $(JADE_CORE_DEBUG_LIBDIRS) $(JADE_CLIENT_DEBUG_LIBDIRS) $(JADE_SERVER_DEBUG_LIBDIRS) $(JADE_EDITOR_DEBUG_LIBDIRS) 
else ifeq ($(BUILD_CONFIG), Release)
	JD_CFLAGS = $(JD_COMMON_CFLAGS) $(JD_RELEASE_CFLAGS)
	JD_LDFLAGS = $(JD_COMMON_LDFLAGS) $(JD_RELEASE_LDFLAGS)

	JADE_CORE_LIBS = $(JADE_CORE_RELEASE_LIBS)
	JADE_CORE_LIBDIRS = $(JADE_CORE_RELEASE_LIBDIRS)

	JADE_CLIENT_LIBS = $(JADE_CORE_RELEASE_LIBS) $(JADE_CLIENT_RELEASE_LIBS)
	JADE_CLIENT_LIBDIRS = $(JADE_CORE_RELEASE_LIBDIRS) $(JADE_CLIENT_RELEASE_LIBDIRS)

	JADE_SERVER_LIBS = $(JADE_CORE_RELEASE_LIBS) $(JADE_SERVER_RELEASE_LIBS)
	JADE_SERVER_LIBDIRS = $(JADE_CORE_RELEASE_LIBDIRS) $(JADE_SERVER_RELEASE_LIBDIRS)

	JADE_EDITOR_LIBS = $(JADE_CORE_RELEASE_LIBS) $(JADE_CLIENT_RELEASE_LIBS) $(JADE_SERVER_RELEASE_LIBS) $(JADE_EDITOR_RELEASE_LIBS)
	JADE_EDITOR_LIBDIRS = $(JADE_CORE_RELEASE_LIBDIRS) $(JADE_CLIENT_RELEASE_LIBDIRS) $(JADE_SERVER_RELEASE_LIBDIRS) $(JADE_EDITOR_RELEASE_LIBDIRS)
else
	$(error BUILD_CONFIG must be either Debug or Release)
endif