include Jade.mk

JADE_EDITOR_SOURCES = $(wildcard $(JADE_EDITOR_SOURCE_DIR)/**.cpp) $(wildcard $(JADE_EDITOR_SOURCE_DIR)/**/**.cpp) $(wildcard $(JADE_EDITOR_SOURCE_DIR)/**/**/**.cpp) $(wildcard $(JADE_EDITOR_SOURCE_DIR)/**/**/**/**.cpp)
JADE_EDITOR_BINARIES = $(JADE_EDITOR_SOURCES:$(JADE_EDITOR_SOURCE_DIR)/%.cpp=$(JADE_EDITOR_BINARY_INTERMEDIATE_DIR)/%.o)
JADE_EDITOR_DEPENDENCIES = $(JADE_EDITOR_SOURCES:$(JADE_EDITOR_SOURCE_DIR)/%.cpp=$(JADE_EDITOR_BINARY_INTERMEDIATE_DIR)/%.d)
JADE_EDITOR_LIBRARIES = $(JADE_CORE_OUTPUT_TARGET) $(JADE_CLIENT_OUTPUT_TARGET) $(JADE_SERVER_OUTPUT_TARGET)

$(JADE_EDITOR_OUTPUT_TARGET): $(JADE_EDITOR_BINARIES) $(JADE_EDITOR_LIBRARIES)
	echo $@
	echo.
	if not exist "$(@D)" mkdir "$(@D)"
	$(JD_COMPILER) $(JADE_EDITOR_BINARIES) -o $@ $(JD_LDFLAGS) $(JADE_EDITOR_LIBS) $(JADE_EDITOR_LIBDIRS)

$(JADE_EDITOR_BINARY_INTERMEDIATE_DIR)/%.o: $(JADE_EDITOR_SOURCE_DIR)/%.cpp
	echo $@
	if not exist "$(@D)" mkdir "$(@D)"
	$(JD_COMPILER) -c $< -o $@ $(JD_CFLAGS) $(JADE_EDITOR_INCLUDE_DIRS)

-include $(JADE_EDITOR_DEPENDENCIES)