include Jade.mk

JADE_CLIENT_SOURCES = $(wildcard $(JADE_CLIENT_SOURCE_DIR)/**.cpp) $(wildcard $(JADE_CLIENT_SOURCE_DIR)/**/**.cpp) $(wildcard $(JADE_CLIENT_SOURCE_DIR)/**/**/**.cpp) $(wildcard $(JADE_CLIENT_SOURCE_DIR)/**/**/**/**.cpp)
JADE_CLIENT_BINARIES = $(JADE_CLIENT_SOURCES:$(JADE_CLIENT_SOURCE_DIR)/%.cpp=$(JADE_CLIENT_BINARY_INTERMEDIATE_DIR)/%.o)
JADE_CLIENT_DEPENDENCIES = $(JADE_CLIENT_SOURCES:$(JADE_CLIENT_SOURCE_DIR)/%.cpp=$(JADE_CLIENT_BINARY_INTERMEDIATE_DIR)/%.d)

$(JADE_CLIENT_OUTPUT_TARGET): $(JADE_CLIENT_BINARIES)
	echo $@
	echo.
	if not exist "$(@D)" mkdir "$(@D)"
	$(JD_ARCHIVE) -rcs $@ $(JADE_CLIENT_BINARIES)

$(JADE_CLIENT_BINARY_INTERMEDIATE_DIR)/%.o: $(JADE_CLIENT_SOURCE_DIR)/%.cpp
	echo $@
	if not exist "$(@D)" mkdir "$(@D)"
	$(JD_COMPILER) -c $< -o $@ $(JD_CFLAGS) $(JADE_CLIENT_INCLUDES)

-include $(JADE_CLIENT_DEPENDENCIES)