include Jade.mk

JADE_SERVER_SOURCES = $(wildcard $(JADE_SERVER_SOURCE_DIR)/**.cpp) $(wildcard $(JADE_SERVER_SOURCE_DIR)/**/**.cpp) $(wildcard $(JADE_SERVER_SOURCE_DIR)/**/**/**.cpp) $(wildcard $(JADE_SERVER_SOURCE_DIR)/**/**/**/**.cpp)
JADE_SERVER_BINARIES = $(JADE_SERVER_SOURCES:$(JADE_SERVER_SOURCE_DIR)/%.cpp=$(JADE_SERVER_BINARY_INTERMEDIATE_DIR)/%.o)
JADE_SERVER_DEPENDENCIES = $(JADE_SERVER_SOURCES:$(JADE_SERVER_SOURCE_DIR)/%.cpp=$(JADE_SERVER_BINARY_INTERMEDIATE_DIR)/%.d)

$(JADE_SERVER_OUTPUT_TARGET): $(JADE_SERVER_BINARIES) $(JADE_SERVER_LIBRARIES)
	echo $@
	echo.
	if not exist "$(@D)" mkdir "$(@D)"
	$(JD_ARCHIVE) -rcs $@ $(JADE_SERVER_BINARIES)

$(JADE_SERVER_BINARY_INTERMEDIATE_DIR)/%.o: $(JADE_SERVER_SOURCE_DIR)/%.cpp
	echo $@
	if not exist "$(@D)" mkdir "$(@D)"
	$(JD_COMPILER) -c $< -o $@ $(JD_CFLAGS) $(JADE_SERVER_INCLUDES)

-include $(JADE_SERVER_DEPENDENCIES)